calibrate_fixed_extrinsics:
  camera:
    "0":
      name: "camera_1"
      serial: "f1380463"
      image_width: 640
      image_height: 480
      image_width_depth: 640
      image_height_depth: 480
    "1":
      name: "camera_2"
      serial: "f1421239"
      image_width: 1280
      image_height: 720
      image_width_depth: 640
      image_height_depth: 480

  tag:
    type: tagStandard52h13
    length: 1.0  # [inches]
    active_pixel_ratio: 0.6  # For details, see https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide
    tag_ids:
      "0": # on table clockwise 45 degrees, on x mark
        pose_t: [0.664, 0, 0]
        pose_r: [[0.7071, 0.7071, 0], [-0.7071, 0.7071, 0], [0, 0, 1]]
      "1": # on grey 30 degrees, facing -y of table
        pose_t: [0.464, -0.25, 0.07]
        pose_r: [[ 0.0,    -1.0,     0.0   ],
                 [ 0.8660,  0.0,    -0.5   ],
                 [ 0.5,     0.0,     0.8660]]
      "5": 
        pose_t: [0.164, 0.2, 0.11]
        pose_r: [[ 0.0,    -0.7071,  0.7071],
                 [ 1.0,     0.0,     0.0   ],
                 [ 0.0,     0.7071,  0.7071]]
      "6":
        pose_t: [0.134, -0.05, 0.0]
        pose_r: [[1, 0, 0],
                 [0, 1, 0],
                 [0, 0, 1]]
  tag_detection:
    num_detection: 4
    display_images: False

  output:
    file_name: workspace_mapping.json
    image_file_name: tag_detection.png

detect_objects_april:
  camera:
    "0":
      name: "camera_1"
      serial: "f1380463"
      image_width: 640
      image_height: 480
    "1":
      name: "camera_2"
      serial: "f1421239"
      image_width: 1280
      image_height: 720
  object_detection:
    tag:
      type: tagStandard52h13
      length: 6.0  # [inches]
      active_pixel_ratio: 0.6
      tag_ids:
        "4":
          label: 'four_hole_base'
          offset: [0.0, 0.039, -0.005]
        "5":
          label: 'four_hole_inserter'
          offset: [0.0, 0.0, -0.005]
    scene:
      type: four_hole_3_classes
      four_hole_3_classes:
        label_names: ['background', 'four_hole_base', 'four_hole_inserter']
    confidence_thresh: 0.9
    display_images: True
  augmentation:
    augment_image: True
    num_augmentations: 16
  output:
    json_file_name: object_detections.json
    image_file_name: object_detections.png

